$ErrorActionPreference = 'Stop'

$marker = 'CHEZMOI_MANAGED_PWSH_PROFILE_LOADER'
$managedDir = Join-Path $HOME '.config\powershell'
$managedProfile = Join-Path $managedDir 'profile.ps1'

$loader = @"
# $marker
# This file is generated by chezmoi.
# Source of truth:
#   $managedProfile
# This loader runs the copied profile from this directory:
#   $PSScriptRoot\profile.ps1

$_localProfile = Join-Path $PSScriptRoot 'profile.ps1'
if (Test-Path -LiteralPath $_localProfile) {
    . $_localProfile
}
"@

$profilePath = $null
try { $profilePath = $PROFILE.CurrentUserAllHosts } catch {}

if ($profilePath) {
    $profileDir = Split-Path -Parent $profilePath
    if ($profileDir -and -not (Test-Path -LiteralPath $profileDir)) {
        New-Item -ItemType Directory -Force -Path $profileDir | Out-Null
    }

    if (Test-Path -LiteralPath $profilePath) {
        $existing = Get-Content -LiteralPath $profilePath -Raw -ErrorAction SilentlyContinue
        $isChezmoiManaged = $existing -and ($existing -match [regex]::Escape($marker))
        $isNonEmpty = $existing -and ($existing.Trim().Length -gt 0)

        if (-not $isChezmoiManaged -and $isNonEmpty) {
            $backup = "$profilePath.chezmoi.bak"
            if (-not (Test-Path -LiteralPath $backup)) {
                Copy-Item -LiteralPath $profilePath -Destination $backup -Force
            }
        }
    }

    [System.IO.File]::WriteAllText(
        $profilePath,
        $loader,
        [System.Text.UTF8Encoding]::new($false)
    )

    if (Test-Path -LiteralPath $managedDir) {
        $sourceFiles = Get-ChildItem -LiteralPath $managedDir -Filter '*.ps1' -File -ErrorAction SilentlyContinue
        foreach ($file in $sourceFiles) {
            $destPath = Join-Path $profileDir $file.Name
            Copy-Item -LiteralPath $file.FullName -Destination $destPath -Force
        }
    }
}
