theme = "dark_plus"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.lsp]
# clangd supports inlay hints; pyright does not advertise inlayHintProvider
display-inlay-hints = true
